# Generated by Django 3.0.8 on 2020-07-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200718_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='hire_date',
            field=models.DateField(verbose_name='Hiring Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period',
            field=models.DateField(verbose_name='Reference Period'),
        ),
        migrations.AlterField(
            model_name='report',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Sales Volume'),
        ),
    ]
